//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class booking_data
{
    public int booking_number { get; set; }
    public string enter_datetime { get; set; }
    public string room { get; set; }
    public int people { get; set; }
    public string check_in_date { get; set; }
    public string check_out_date { get; set; }
    public int price { get; set; }
    public string first_name { get; set; }
    public string last_name { get; set; }
    public string email { get; set; }
    public string phone { get; set; }
    public string payment_method { get; set; }
}

public partial class employee
{
    public int employee_number { get; set; }
    public string employee_name { get; set; }
    public string employee_password { get; set; }
    public string group { get; set; }
}
